name: astrid
favicon: null
layout_spectrum: 0.0860543034505099
typography_spectrum: 0.16415
title: Where I took notes of my favorite food and travel places
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3e6d3'
    - '#a68c53'
    - '#060606'
    - '#765630'
    - '#f8ab00'
  brandStrength: 0.15605277009308338
  lightness: 0.6439299259800464
  saturation: 0.41009484068490565
  rhythmicContrast: 0.5705844350159168
purpose: []
